name: apk - build branch and release


on:
  push:
    branches:
      - main


jobs:

  android:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[android]')
    permissions:
      contents: write

    steps:
      - name: Set variables
        run: |
          TAG_NAME="${GITHUB_REF_NAME}-${GITHUB_SHA::7}"
          APK_NAME="App-${TAG_NAME}.apk"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV

      - name: Echo variables
        run: |
          echo $TAG_NAME
          echo $IPA_NAME
