name: build and release


on:
  push:
    branches:
      - main


jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.vars.outputs.tag_name }}
      release_name: ${{ steps.vars.outputs.release_name }}

    steps:
      - name: Set variables
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF_NAME}-${GITHUB_SHA::7}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "release_name=App-${TAG_NAME}" >> $GITHUB_OUTPUT

  android:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v7
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build ipa --no-codesign
      - run: zip -r ios.zip build/ios/archive/
      - uses: actions/upload-artifact@v7
        with:
          name: ios
          path: ios.zip

  web:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build web
      - run: zip -r web.zip build/web/
      - uses: actions/upload-artifact@v7
        with:
          name: web
          path: web.zip

  linux:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux
      - run: zip -r linux.zip build/linux/x64/release/bundle/
      - uses: actions/upload-artifact@v7
        with:
          name: linux
          path: linux.zip

  macos:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build macos
      - run: zip -r macos.zip build/macos/Build/Products/Release/
      - uses: actions/upload-artifact@v7
        with:
          name: macos
          path: macos.zip

  windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - run: Compress-Archive -Path build/windows/x64/runner/Release/ -DestinationPath windows.zip
      - uses: actions/upload-artifact@v7
        with:
          name: windows
          path: windows.zip

  finalize:
    needs: [setup, android, ios, web, linux, macos, windows]
    runs-on: ubuntu-latest

    steps:
      - name: Echo all variables
        run: |
          echo "tag_name=${{ needs.setup.outputs.tag_name }}"
          echo "release_name=${{ needs.setup.outputs.release_name }}"

  publish-android:
    needs: [setup, finalize]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          name: ${{ needs.setup.outputs.release_name }}
          files: app-debug.apk

  publish-ios:
    needs: [setup, finalize]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ios
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          name: ${{ needs.setup.outputs.release_name }}
          files: ios.zip

  publish-web:
    needs: [setup, finalize]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          name: ${{ needs.setup.outputs.release_name }}
          files: web.zip

  publish-linux:
    needs: [setup, finalize]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          name: ${{ needs.setup.outputs.release_name }}
          files: linux.zip

  publish-macos:
    needs: [setup, finalize]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: macos
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          name: ${{ needs.setup.outputs.release_name }}
          files: macos.zip

  publish-windows:
    needs: [setup, finalize]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windows
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          name: ${{ needs.setup.outputs.release_name }}
          files: windows.zip
